# Generated by Django 4.2.5 on 2023-09-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskMaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='action_elaborated',
            field=models.CharField(default='Test', max_length=255),
            preserve_default=False,
        ),
    ]
