# Generated by Django 4.2.5 on 2023-10-04 12:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskMaster', '0003_alter_task_assigned_to_alter_task_types_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='assigned_to',
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(related_name='tasks_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
